#!/usr/bin/env bash

export ydb_log=/tmp/yottadb/r1.30_aarch64
export gtm_log=/tmp/yottadb/r1.30_aarch64
export gtm_repl_instance=/root/.yottadb/r1.30_aarch64/g/yottadb.repl
export ydb_repl_instance=/root/.yottadb/r1.30_aarch64/g/yottadb.repl
export ydb_gbldir=/root/.yottadb/r1.30_aarch64/g/yottadb.gld
export ydb_dir=/root/.yottadb
export gtmver='V6.3-008_aarch64'
export ydb_rel=r1.30_aarch64
export gtmgbldir=/root/.yottadb/r1.30_aarch64/g/yottadb.gld
export ydb_routines="/root/.yottadb/r1.30_aarch64/o*(/root/.yottadb/r1.30_aarch64/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmroutines="/root/.yottadb/r1.30_aarch64/o*(/root/.yottadb/r1.30_aarch64/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmdir=/root/.fis-gtm
export ydb_tmp=/tmp/yottadb/r1.30_aarch64
export gtm_tmp=/tmp/yottadb/r1.30_aarch64
export gtm_dist=/usr/local/lib/yottadb/r130
export ydb_dist=/usr/local/lib/yottadb/r130

$ydb_dist/mumps -dir

